-- MariaDB schema for Library Management System
CREATE TABLE IF NOT EXISTS Books (
  BookID INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(255) NOT NULL,
  Author VARCHAR(255) NOT NULL,
  ISBN VARCHAR(20) NOT NULL UNIQUE,
  PublishYear INT NULL,
  Genre VARCHAR(100) NULL,
  Available TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Members (
  MemberID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Phone VARCHAR(50) NULL,
  JoinDate DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Transactions (
  TransactionID INT AUTO_INCREMENT PRIMARY KEY,
  BookID INT NOT NULL,
  MemberID INT NOT NULL,
  BorrowDate DATE NOT NULL,
  ReturnDate DATE NULL,
  Status VARCHAR(50) NOT NULL,
  CONSTRAINT FK_Transactions_Books FOREIGN KEY (BookID) REFERENCES Books(BookID) ON DELETE CASCADE,
  CONSTRAINT FK_Transactions_Members FOREIGN KEY (MemberID) REFERENCES Members(MemberID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
