'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My
    <Global.System.Runtime.CompilerServices.CompilerGenerated()> _
    <Global.System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")> _
    Friend NotInheritable Partial Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property RememberedUsername() As String
            Get
                Return CType(Me("RememberedUsername"), String)
            End Get
            Set
                Me("RememberedUsername") = value
            End Set
        End Property
    End Class
End Namespace
